export const MESSAGE_CONSTANTS = {
    MAX_MESSAGES: 10,
    RECENT_MESSAGE_COUNT: 3,
    CHAT_HISTORY_COUNT: 5,
    INTEREST_DECAY_TIME: 5 * 60 * 1000, // 5 minutes
    PARTIAL_INTEREST_DECAY: 3 * 60 * 1000, // 3 minutes
    DEFAULT_SIMILARITY_THRESHOLD: 0.3,
    DEFAULT_SIMILARITY_THRESHOLD_FOLLOW_UPS: 0.2,
} as const;





