name: ci
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 10.14.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23.3.0"
                  cache: "pnpm"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm install -r --no-frozen-lockfile

            - name: Run Prettier
              run: pnpm run prettier --check .

            - name: Run Linter
              run: pnpm run lint

            - name: Create test env file
              run: |
                  echo "TEST_DATABASE_CLIENT=sqlite" > packages/core/.env.test
                  echo "NODE_ENV=test" >> packages/core/.env.test

            - name: Build packages
              run: pnpm run build

            - name: Run tests
              run: pnpm test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
